# ruff: noqa: RUF001
"""Vorgefertigte Bewerbungstext-Vorlagen pro Ausbildungsspezialität.

Verfügbar als Premium-Feature für Pro- und Max-Abonnenten. Jede Vorlage
verwendet ``{{company}}`` als Platzhalter, der beim Versand durch den
Firmennamen aus der BA-Ausschreibung ersetzt wird.
"""

from __future__ import annotations

from typing import Final

# specialty keyword -> ready-to-use German cover-letter body.
# All texts intentionally avoid {{name}} so they work even before the user
# sets up their signature; the SMTP "From" header carries the sender name.
TEMPLATES: Final[dict[str, str]] = {
    "Pflegefachmann": (
        "Sehr geehrte Damen und Herren,\n\n"
        "mit großem Interesse habe ich Ihre Stellenausschreibung für eine "
        "Ausbildung zur Pflegefachkraft bei {{company}} gelesen und möchte "
        "mich hiermit um einen Ausbildungsplatz bewerben.\n\n"
        "Der Pflegeberuf ist für mich weit mehr als nur eine Tätigkeit – er ist "
        "Berufung. Der Umgang mit Menschen, Verantwortungsbewusstsein und der "
        "Wunsch, anderen in schwierigen Lebensphasen beizustehen, motivieren "
        "mich täglich. Durch Praktika und persönliche Erfahrungen konnte ich "
        "bereits erste Einblicke in den Pflegealltag gewinnen und meine "
        "Eignung für diesen Beruf bestätigen.\n\n"
        "Zu meinen Stärken zählen Empathie, Belastbarkeit und Teamfähigkeit. "
        "Ich arbeite zuverlässig, lerne schnell und bringe die nötige "
        "Geduld mit, um auf die individuellen Bedürfnisse von Patientinnen "
        "und Patienten einzugehen.\n\n"
        "Über eine Einladung zu einem persönlichen Vorstellungsgespräch "
        "würde ich mich sehr freuen.\n\n"
        "Mit freundlichen Grüßen"
    ),
    "Krankenpflegehelfer": (
        "Sehr geehrte Damen und Herren,\n\n"
        "hiermit bewerbe ich mich um einen Ausbildungsplatz als "
        "Krankenpflegehelfer/in bei {{company}}. Auf Ihre Einrichtung wurde "
        "ich über die Bundesagentur für Arbeit aufmerksam und war sofort "
        "begeistert.\n\n"
        "Die Arbeit mit pflegebedürftigen Menschen erfüllt mich mit Sinn. "
        "Ich möchte aktiv dazu beitragen, dass sich Patientinnen und "
        "Patienten in Ihrem Haus wohl und gut versorgt fühlen. Verantwortungs"
        "bewusstsein, Geduld und ein freundliches Auftreten gehören zu "
        "meinen wichtigsten Eigenschaften.\n\n"
        "Ich bin körperlich belastbar, arbeite gerne im Team und kann gut "
        "mit Stresssituationen umgehen. Eine Ausbildung in Ihrem Haus wäre "
        "für mich der perfekte Einstieg in den Pflegeberuf.\n\n"
        "Ich freue mich auf Ihre Rückmeldung und stehe für ein Vorstellungs"
        "gespräch jederzeit gerne zur Verfügung.\n\n"
        "Mit freundlichen Grüßen"
    ),
    "Notfallsanitäter": (
        "Sehr geehrte Damen und Herren,\n\n"
        "mit großem Interesse bewerbe ich mich bei {{company}} um einen "
        "Ausbildungsplatz zum Notfallsanitäter.\n\n"
        "Schnell denken, präzise handeln und auch unter Druck einen kühlen "
        "Kopf bewahren – diese Eigenschaften zeichnen den Beruf des "
        "Notfallsanitäters aus und sind genau die Anforderungen, die mich "
        "an diesem Beruf reizen. Menschen in akuten Notlagen helfen zu "
        "können, ist für mich eine sinnstiftende Aufgabe.\n\n"
        "Ich bin körperlich fit, belastbar und arbeite gerne im Team. "
        "Verantwortung zu übernehmen liegt mir, ebenso wie der respektvolle "
        "Umgang mit Menschen in Ausnahmesituationen. Erste Einblicke in den "
        "Rettungsdienst konnte ich bereits durch Erste-Hilfe-Kurse und "
        "ehrenamtliches Engagement sammeln.\n\n"
        "Ich würde mich sehr freuen, Sie in einem persönlichen Gespräch "
        "von meiner Motivation überzeugen zu dürfen.\n\n"
        "Mit freundlichen Grüßen"
    ),
    "Mechatroniker": (
        "Sehr geehrte Damen und Herren,\n\n"
        "hiermit bewerbe ich mich um einen Ausbildungsplatz als "
        "Mechatroniker/in bei {{company}}.\n\n"
        "Schon früh hat mich die Verbindung von Mechanik, Elektronik und "
        "Informatik begeistert. Ich tüftle gerne an technischen Problemen, "
        "verstehe komplexe Systeme und finde es spannend, wie aus "
        "Einzelkomponenten funktionierende Maschinen entstehen. Eine "
        "Ausbildung in Ihrem Unternehmen wäre für mich die ideale Möglich"
        "keit, dieses Interesse in einen Beruf zu verwandeln.\n\n"
        "Zu meinen Stärken zählen technisches Verständnis, sorgfältiges "
        "Arbeiten und Teamfähigkeit. Mathematik und Physik liegen mir, und "
        "ich bin bereit, mich anspruchsvollen Aufgaben zu stellen.\n\n"
        "Über eine Einladung zu einem Vorstellungsgespräch würde ich mich "
        "sehr freuen.\n\n"
        "Mit freundlichen Grüßen"
    ),
    "Fachinformatiker für Anwendungsentwicklung": (
        "Sehr geehrte Damen und Herren,\n\n"
        "mit großem Interesse bewerbe ich mich um einen Ausbildungsplatz "
        "als Fachinformatiker für Anwendungsentwicklung bei {{company}}.\n\n"
        "Programmieren ist für mich nicht nur ein Beruf, sondern auch ein "
        "Hobby. Das logische Denken, das schrittweise Lösen komplexer "
        "Probleme und das Erschaffen funktionierender Software begeistern "
        "mich. Erste Erfahrungen mit Programmiersprachen wie Python und "
        "HTML/CSS konnte ich bereits sammeln und arbeite stetig daran, "
        "mein Wissen zu erweitern.\n\n"
        "Zu meinen Stärken gehören analytisches Denken, Lernbereitschaft "
        "und Teamfähigkeit. Ich bin neugierig, arbeite strukturiert und "
        "lasse mich von Herausforderungen nicht abschrecken.\n\n"
        "Über die Möglichkeit, Sie persönlich kennenzulernen, würde ich "
        "mich sehr freuen.\n\n"
        "Mit freundlichen Grüßen"
    ),
    "Fachinformatiker für Systemintegration": (
        "Sehr geehrte Damen und Herren,\n\n"
        "hiermit bewerbe ich mich um einen Ausbildungsplatz als "
        "Fachinformatiker für Systemintegration bei {{company}}.\n\n"
        "Die Welt der IT-Infrastruktur fasziniert mich: Netzwerke planen, "
        "Server einrichten und dafür sorgen, dass alles reibungslos läuft. "
        "Ich beschäftige mich bereits in meiner Freizeit mit Hardware, "
        "Betriebssystemen und kleineren Heimnetzwerken. Eine Ausbildung in "
        "Ihrem Unternehmen wäre für mich die ideale Gelegenheit, dieses "
        "Interesse professionell zu vertiefen.\n\n"
        "Ich bringe technisches Verständnis, Sorgfalt und eine ausgeprägte "
        "Problemlösungskompetenz mit. Auch unter Druck arbeite ich ruhig "
        "und strukturiert. Der Umgang mit Kollegen und Anwendern macht "
        "mir Freude.\n\n"
        "Über eine Einladung zu einem persönlichen Vorstellungsgespräch "
        "würde ich mich sehr freuen.\n\n"
        "Mit freundlichen Grüßen"
    ),
    "Kaufmann": (
        "Sehr geehrte Damen und Herren,\n\n"
        "mit großem Interesse bewerbe ich mich um einen Ausbildungsplatz "
        "als Kaufmann/-frau bei {{company}}.\n\n"
        "Kaufmännische Abläufe, der Umgang mit Kunden und das Verständnis "
        "wirtschaftlicher Zusammenhänge interessieren mich seit Langem. Ich "
        "möchte einen Beruf erlernen, in dem Genauigkeit, Verantwortung und "
        "Kommunikation gleichermaßen gefragt sind. Ihr Unternehmen hat mich "
        "durch sein Profil und seine Werte besonders angesprochen.\n\n"
        "Ich bin zuverlässig, organisiert und arbeite gerne mit Menschen. "
        "Der Umgang mit Zahlen liegt mir, und ich kann mich schnell in neue "
        "Aufgabenbereiche einarbeiten. Auch unter Termindruck behalte ich "
        "den Überblick.\n\n"
        "Über die Einladung zu einem persönlichen Gespräch würde ich mich "
        "sehr freuen.\n\n"
        "Mit freundlichen Grüßen"
    ),
    "Bankkaufmann": (
        "Sehr geehrte Damen und Herren,\n\n"
        "mit großem Interesse habe ich Ihre Ausschreibung für eine "
        "Ausbildung zum Bankkaufmann gelesen und möchte mich hiermit bei "
        "{{company}} bewerben.\n\n"
        "Der Bankberuf vereint für mich alles, was mich an einer kaufmänni"
        "schen Tätigkeit reizt: kundenorientierte Beratung, präzises "
        "Arbeiten mit Zahlen und ein dynamisches wirtschaftliches Umfeld. "
        "Vertrauen und Diskretion sind in diesem Beruf entscheidend – Werte, "
        "die ich auch persönlich hochhalte.\n\n"
        "Zu meinen Stärken zählen ein gepflegtes Auftreten, Kommunikations"
        "stärke und ein gutes Zahlenverständnis. Ich arbeite zuverlässig, "
        "kann mich gut in Kundinnen und Kunden hineinversetzen und behalte "
        "auch in komplexen Situationen einen klaren Kopf.\n\n"
        "Über die Gelegenheit, mich in einem persönlichen Gespräch "
        "vorzustellen, würde ich mich sehr freuen.\n\n"
        "Mit freundlichen Grüßen"
    ),
    "Hotelfachmann": (
        "Sehr geehrte Damen und Herren,\n\n"
        "hiermit bewerbe ich mich um einen Ausbildungsplatz als "
        "Hotelfachmann/-frau bei {{company}}.\n\n"
        "Die Hotellerie ist für mich ein Beruf, in dem Gastfreundschaft, "
        "Organisation und der Kontakt zu Menschen aus aller Welt zusammen"
        "kommen. Ich liebe es, Gästen unvergessliche Aufenthalte zu "
        "ermöglichen und an einem Ort zu arbeiten, an dem kein Tag dem "
        "anderen gleicht. Ihr Haus hat mich besonders überzeugt.\n\n"
        "Zu meinen Stärken gehören Freundlichkeit, Stressresistenz und ein "
        "gepflegtes Auftreten. Ich bin teamfähig, flexibel und beherrsche "
        "die deutsche Sprache sicher; zusätzliche Sprachkenntnisse bringe "
        "ich ebenfalls mit.\n\n"
        "Über eine Einladung zu einem persönlichen Vorstellungsgespräch "
        "würde ich mich sehr freuen.\n\n"
        "Mit freundlichen Grüßen"
    ),
    "Verkäufer": (
        "Sehr geehrte Damen und Herren,\n\n"
        "hiermit bewerbe ich mich um einen Ausbildungsplatz als "
        "Verkäufer/in bei {{company}}.\n\n"
        "Der Kontakt zu Kundinnen und Kunden, Beratung und der lebhafte "
        "Alltag im Einzelhandel begeistern mich. Ich bin kommunikativ, "
        "freundlich und habe Freude daran, anderen Menschen weiterzuhelfen. "
        "Ihre Filiale ist mir bereits als Kunde positiv aufgefallen, und "
        "ich würde gerne ein Teil Ihres Teams werden.\n\n"
        "Ich bin belastbar, zuverlässig und arbeite gerne im Team. Auch "
        "unter Zeitdruck behalte ich einen kühlen Kopf und ein freundliches "
        "Auftreten. Der Umgang mit Geld und Kasse fällt mir leicht.\n\n"
        "Ich freue mich sehr auf Ihre Rückmeldung und ein persönliches "
        "Kennenlernen.\n\n"
        "Mit freundlichen Grüßen"
    ),
    "Elektroniker": (
        "Sehr geehrte Damen und Herren,\n\n"
        "mit großem Interesse bewerbe ich mich um einen Ausbildungsplatz "
        "als Elektroniker/in bei {{company}}.\n\n"
        "Schon als Kind habe ich gerne Geräte auseinandergenommen, um zu "
        "verstehen, wie sie funktionieren. Heute begeistert mich besonders "
        "die Vielseitigkeit des Elektronikerberufs: vom Installieren bis "
        "zum Programmieren, von der Fehlersuche bis zur Inbetriebnahme. "
        "Ihre Firma bietet genau das Umfeld, in dem ich diese Faszination "
        "in einen Beruf umsetzen möchte.\n\n"
        "Zu meinen Stärken zählen technisches Verständnis, sorgfältiges "
        "Arbeiten und logisches Denken. Ich arbeite sicher mit den Händen, "
        "halte mich strikt an Sicherheitsvorschriften und lerne schnell.\n\n"
        "Über eine Einladung zu einem Vorstellungsgespräch würde ich mich "
        "sehr freuen.\n\n"
        "Mit freundlichen Grüßen"
    ),
    "Bäcker": (
        "Sehr geehrte Damen und Herren,\n\n"
        "hiermit bewerbe ich mich um einen Ausbildungsplatz als Bäcker/in "
        "in Ihrer Bäckerei {{company}}.\n\n"
        "Das Bäckerhandwerk hat mich schon immer fasziniert: aus wenigen "
        "Zutaten entstehen Brote, Brötchen und Backwaren, die Menschen "
        "tagtäglich Freude bereiten. Das frühe Aufstehen schreckt mich "
        "nicht ab – im Gegenteil, ich genieße die ruhige Atmosphäre der "
        "Morgenstunden und das Gefühl, etwas mit den eigenen Händen zu "
        "erschaffen.\n\n"
        "Ich bin körperlich belastbar, zuverlässig und arbeite sorgfältig "
        "und hygienisch. Teamarbeit liegt mir, und ich bin bereit, das "
        "traditionelle Handwerk von Grund auf zu lernen.\n\n"
        "Ich freue mich auf die Möglichkeit, mich in einem persönlichen "
        "Gespräch vorzustellen.\n\n"
        "Mit freundlichen Grüßen"
    ),
    "Koch": (
        "Sehr geehrte Damen und Herren,\n\n"
        "mit großem Interesse bewerbe ich mich um einen Ausbildungsplatz "
        "als Koch/Köchin bei {{company}}.\n\n"
        "Kochen ist für mich Leidenschaft und Kreativität in einem. Aus "
        "frischen Zutaten Gerichte zu zaubern, die Gäste begeistern, ist "
        "genau das, was ich beruflich machen möchte. Ihre Küche steht für "
        "Qualität und Anspruch – Eigenschaften, die mich besonders an einer "
        "Ausbildung in Ihrem Haus reizen.\n\n"
        "Ich bin belastbar, arbeite gerne im Team und behalte auch in "
        "hektischen Situationen einen klaren Kopf. Sauberkeit, Pünktlichkeit "
        "und die Bereitschaft, anzupacken, sind für mich selbstverständlich. "
        "Erste Erfahrungen in der Küche konnte ich bereits sammeln und so "
        "feststellen, dass dieser Beruf perfekt zu mir passt.\n\n"
        "Über eine Einladung zu einem persönlichen Gespräch würde ich mich "
        "sehr freuen.\n\n"
        "Mit freundlichen Grüßen"
    ),
}


def template_for(specialty_keyword: str) -> str | None:
    """Return the prepared template for a specialty, or None if unsupported."""
    return TEMPLATES.get(specialty_keyword)
